apiVersion: apps/v1
kind: Deployment
metadata:
  name: user12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user12
  template:
    metadata:
      labels:
        app: user12
    spec:
      containers:
        - name: user12-server
          image: ghcr.io/pumpiya/piyapu
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user12-service
  labels:
    app: user12-service
spec:
  selector:
    app: user12
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
